/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CompanySchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'domain', 'id', 'isActive', 'name', 'phone', 'updatedAt'] as const
  $columns = CompanySchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domain: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CompanyMembershipSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'id', 'isDefault', 'role', 'systemUserId', 'updatedAt'] as const
  $columns = CompanyMembershipSchema.$columns
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column()
  declare role: any
  @column()
  declare systemUserId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ConnectionSchema extends BaseModel {
  static $columns = ['bandwidth', 'cableCategory', 'cableLength', 'companyId', 'connectionStatus', 'connectionType', 'createdAt', 'description', 'fiberConnector', 'fiberType', 'id', 'mediumType', 'metadata', 'sourcePortId', 'targetPortId', 'updatedAt', 'wifiBand', 'wifiSecurity', 'wifiSsid', 'wifiStandard'] as const
  $columns = ConnectionSchema.$columns
  @column()
  declare bandwidth: string | null
  @column()
  declare cableCategory: string | null
  @column()
  declare cableLength: string | null
  @column()
  declare companyId: string
  @column()
  declare connectionStatus: string
  @column()
  declare connectionType: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare fiberConnector: string | null
  @column()
  declare fiberType: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mediumType: string
  @column()
  declare metadata: any | null
  @column()
  declare sourcePortId: string
  @column()
  declare targetPortId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare wifiBand: string | null
  @column()
  declare wifiSecurity: string | null
  @column()
  declare wifiSsid: string | null
  @column()
  declare wifiStandard: string | null
}

export class DepartmentSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = DepartmentSchema.$columns
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceCredentialSchema extends BaseModel {
  static $columns = ['communityString', 'createdAt', 'credentialType', 'deviceId', 'id', 'notes', 'password', 'port', 'updatedAt', 'username'] as const
  $columns = DeviceCredentialSchema.$columns
  @column()
  declare communityString: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credentialType: any
  @column()
  declare deviceId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare port: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string | null
}

export class DeviceTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'icon', 'id', 'name', 'updatedAt'] as const
  $columns = DeviceTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'deviceTypeId', 'firmwareVersion', 'hostname', 'id', 'ipAddress', 'location', 'macAddress', 'manufacturer', 'model', 'name', 'notes', 'serialNumber', 'status', 'updatedAt'] as const
  $columns = DeviceSchema.$columns
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceTypeId: string
  @column()
  declare firmwareVersion: string | null
  @column()
  declare hostname: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare location: string | null
  @column()
  declare macAddress: string | null
  @column()
  declare manufacturer: string | null
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare serialNumber: string | null
  @column()
  declare status: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeCredentialSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'employeeId', 'id', 'kind', 'label', 'notes', 'passwordCiphertext', 'updatedAt', 'username'] as const
  $columns = EmployeeCredentialSchema.$columns
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare employeeId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: any
  @column()
  declare label: string | null
  @column()
  declare notes: string | null
  @column()
  declare passwordCiphertext: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}

export class EmployeeDeviceSchema extends BaseModel {
  static $columns = ['assignedAt', 'createdAt', 'deviceId', 'employeeId', 'id', 'role', 'updatedAt'] as const
  $columns = EmployeeDeviceSchema.$columns
  @column.dateTime()
  declare assignedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceId: string
  @column()
  declare employeeId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'departmentId', 'email', 'firstName', 'id', 'lastName', 'phone', 'position', 'updatedAt'] as const
  $columns = EmployeeSchema.$columns
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare departmentId: string | null
  @column()
  declare email: string | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastName: string
  @column()
  declare phone: string | null
  @column()
  declare position: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NetworkSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'description', 'dhcpEnabled', 'dnsPrimary', 'dnsSecondary', 'gateway', 'id', 'name', 'subnet', 'updatedAt', 'vlanId'] as const
  $columns = NetworkSchema.$columns
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare dhcpEnabled: boolean
  @column()
  declare dnsPrimary: string | null
  @column()
  declare dnsSecondary: string | null
  @column()
  declare gateway: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare subnet: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vlanId: string | null
}

export class PortVlanSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isTagged', 'portId', 'updatedAt', 'vlanId'] as const
  $columns = PortVlanSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isTagged: boolean
  @column()
  declare portId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vlanId: string
}

export class PortSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'deviceId', 'id', 'name', 'portNumber', 'portType', 'speed', 'status', 'updatedAt'] as const
  $columns = PortSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare deviceId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare portNumber: number
  @column()
  declare portType: any
  @column()
  declare speed: string | null
  @column()
  declare status: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SystemUserSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'email', 'firstName', 'id', 'isActive', 'lastName', 'password', 'role', 'updatedAt'] as const
  $columns = SystemUserSchema.$columns
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TopologyCanvasLayoutSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'id', 'labelOffsets', 'layer', 'nodeParents', 'nodePositions', 'scope', 'updatedAt', 'workAreas'] as const
  $columns = TopologyCanvasLayoutSchema.$columns
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare labelOffsets: any
  @column()
  declare layer: string
  @column()
  declare nodeParents: any
  @column()
  declare nodePositions: any
  @column()
  declare scope: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare workAreas: any
}

export class VlanSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'description', 'id', 'name', 'updatedAt', 'vlanId'] as const
  $columns = VlanSchema.$columns
  @column()
  declare companyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vlanId: number
}
