/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AreaSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'deletedAt', 'deletedBy', 'id', 'name', 'notes', 'siteId', 'updatedAt', 'updatedBy'] as const
  $columns = AreaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare siteId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class AttachmentSchema extends BaseModel {
  static $columns = ['attachableId', 'attachableType', 'createdAt', 'createdBy', 'deletedAt', 'deletedBy', 'description', 'id', 'kind', 'mimeType', 'originalFilename', 'projectId', 'sizeBytes', 'storagePath', 'title', 'updatedAt', 'updatedBy', 'url'] as const
  $columns = AttachmentSchema.$columns
  @column()
  declare attachableId: string
  @column()
  declare attachableType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: string | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare mimeType: string | null
  @column()
  declare originalFilename: string | null
  @column()
  declare projectId: string
  @column()
  declare sizeBytes: bigint | number | null
  @column()
  declare storagePath: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
  @column()
  declare url: string | null
}

export class CableTypeSchema extends BaseModel {
  static $columns = ['code', 'color', 'createdAt', 'defaultCategory', 'defaultFiberType', 'description', 'id', 'mediumFamily', 'name', 'sortOrder', 'updatedAt'] as const
  $columns = CableTypeSchema.$columns
  @column()
  declare code: string
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultCategory: string | null
  @column()
  declare defaultFiberType: string | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mediumFamily: string
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ConnectionSchema extends BaseModel {
  static $columns = ['bandwidth', 'cableCategory', 'cableLength', 'cableTypeId', 'connectionStatus', 'connectionType', 'createdAt', 'createdBy', 'deletedAt', 'deletedBy', 'description', 'fiberConnector', 'fiberType', 'id', 'mediumType', 'metadata', 'projectId', 'sourceFace', 'sourcePortId', 'targetFace', 'targetPortId', 'updatedAt', 'updatedBy', 'wifiBand', 'wifiSecurity', 'wifiSsid', 'wifiStandard'] as const
  $columns = ConnectionSchema.$columns
  @column()
  declare bandwidth: string | null
  @column()
  declare cableCategory: string | null
  @column()
  declare cableLength: string | null
  @column()
  declare cableTypeId: string | null
  @column()
  declare connectionStatus: string
  @column()
  declare connectionType: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: string | null
  @column()
  declare description: string | null
  @column()
  declare fiberConnector: string | null
  @column()
  declare fiberType: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mediumType: string
  @column()
  declare metadata: any | null
  @column()
  declare projectId: string
  @column()
  declare sourceFace: string
  @column()
  declare sourcePortId: string
  @column()
  declare targetFace: string
  @column()
  declare targetPortId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
  @column()
  declare wifiBand: string | null
  @column()
  declare wifiSecurity: string | null
  @column()
  declare wifiSsid: string | null
  @column()
  declare wifiStandard: string | null
}

export class DepartmentSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'projectId', 'updatedAt'] as const
  $columns = DepartmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceCredentialSchema extends BaseModel {
  static $columns = ['communityString', 'createdAt', 'credentialType', 'deviceId', 'id', 'notes', 'password', 'port', 'updatedAt', 'username'] as const
  $columns = DeviceCredentialSchema.$columns
  @column()
  declare communityString: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credentialType: any
  @column()
  declare deviceId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare port: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string | null
}

export class DeviceTemplatePortSchema extends BaseModel {
  static $columns = ['chassisFace', 'createdAt', 'description', 'deviceTemplateId', 'id', 'isPassthrough', 'name', 'portNumber', 'portType', 'speed', 'updatedAt'] as const
  $columns = DeviceTemplatePortSchema.$columns
  @column()
  declare chassisFace: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare deviceTemplateId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isPassthrough: boolean
  @column()
  declare name: string
  @column()
  declare portNumber: number
  @column()
  declare portType: string
  @column()
  declare speed: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceTemplateSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'customFields', 'deletedAt', 'deletedBy', 'deviceTypeId', 'frontViewUrl', 'id', 'imageUrl', 'isFullDepth', 'manufacturer', 'model', 'name', 'notes', 'powerConsumptionW', 'rackUnits', 'rearViewUrl', 'updatedAt', 'updatedBy', 'weightKg'] as const
  $columns = DeviceTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column()
  declare customFields: any
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: string | null
  @column()
  declare deviceTypeId: string
  @column()
  declare frontViewUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageUrl: string | null
  @column()
  declare isFullDepth: boolean
  @column()
  declare manufacturer: string | null
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare powerConsumptionW: string | null
  @column()
  declare rackUnits: number | null
  @column()
  declare rearViewUrl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
  @column()
  declare weightKg: string | null
}

export class DeviceTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'icon', 'id', 'name', 'updatedAt'] as const
  $columns = DeviceTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceSchema extends BaseModel {
  static $columns = ['areaId', 'createdAt', 'createdBy', 'deletedAt', 'deletedBy', 'deviceTemplateId', 'deviceTypeId', 'firmwareVersion', 'hostname', 'id', 'ipAddress', 'location', 'macAddress', 'manufacturer', 'model', 'name', 'notes', 'projectId', 'rackFace', 'rackId', 'rackUnitStart', 'serialNumber', 'shelfHeightU', 'shelfSlotStart', 'shelfWidthSlots', 'siteId', 'status', 'supportedByAccessoryId', 'updatedAt', 'updatedBy'] as const
  $columns = DeviceSchema.$columns
  @column()
  declare areaId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: string | null
  @column()
  declare deviceTemplateId: string
  @column()
  declare deviceTypeId: string
  @column()
  declare firmwareVersion: string | null
  @column()
  declare hostname: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare location: string | null
  @column()
  declare macAddress: string | null
  @column()
  declare manufacturer: string | null
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare projectId: string
  @column()
  declare rackFace: string | null
  @column()
  declare rackId: string | null
  @column()
  declare rackUnitStart: number | null
  @column()
  declare serialNumber: string | null
  @column()
  declare shelfHeightU: number | null
  @column()
  declare shelfSlotStart: number | null
  @column()
  declare shelfWidthSlots: number | null
  @column()
  declare siteId: string | null
  @column()
  declare status: any
  @column()
  declare supportedByAccessoryId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class EmployeeCredentialSchema extends BaseModel {
  static $columns = ['createdAt', 'employeeId', 'id', 'kind', 'label', 'notes', 'passwordCiphertext', 'projectId', 'updatedAt', 'username'] as const
  $columns = EmployeeCredentialSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare employeeId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: any
  @column()
  declare label: string | null
  @column()
  declare notes: string | null
  @column()
  declare passwordCiphertext: string
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}

export class EmployeeDeviceSchema extends BaseModel {
  static $columns = ['assignedAt', 'createdAt', 'deviceId', 'employeeId', 'id', 'role', 'updatedAt'] as const
  $columns = EmployeeDeviceSchema.$columns
  @column.dateTime()
  declare assignedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceId: string
  @column()
  declare employeeId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeSchema extends BaseModel {
  static $columns = ['createdAt', 'departmentId', 'email', 'firstName', 'id', 'lastName', 'phone', 'position', 'projectId', 'updatedAt'] as const
  $columns = EmployeeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare departmentId: string | null
  @column()
  declare email: string | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastName: string
  @column()
  declare phone: string | null
  @column()
  declare position: string | null
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NetworkSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'dhcpEnabled', 'dnsPrimary', 'dnsSecondary', 'gateway', 'id', 'name', 'projectId', 'subnet', 'updatedAt', 'vlanId'] as const
  $columns = NetworkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare dhcpEnabled: boolean
  @column()
  declare dnsPrimary: string | null
  @column()
  declare dnsSecondary: string | null
  @column()
  declare gateway: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare projectId: string
  @column()
  declare subnet: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vlanId: string | null
}

export class PortTypeSchema extends BaseModel {
  static $columns = ['code', 'color', 'createdAt', 'defaultSpeed', 'description', 'direction', 'icon', 'id', 'name', 'updatedAt'] as const
  $columns = PortTypeSchema.$columns
  @column()
  declare code: string
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultSpeed: string | null
  @column()
  declare description: string | null
  @column()
  declare direction: string
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PortVlanSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isTagged', 'portId', 'updatedAt', 'vlanId'] as const
  $columns = PortVlanSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isTagged: boolean
  @column()
  declare portId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vlanId: string
}

export class PortSchema extends BaseModel {
  static $columns = ['chassisFace', 'createdAt', 'description', 'deviceId', 'id', 'isPassthrough', 'name', 'portNumber', 'portType', 'speed', 'status', 'updatedAt'] as const
  $columns = PortSchema.$columns
  @column()
  declare chassisFace: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare deviceId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isPassthrough: boolean
  @column()
  declare name: string
  @column()
  declare portNumber: number
  @column()
  declare portType: string
  @column()
  declare speed: string | null
  @column()
  declare status: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProjectMembershipSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isDefault', 'projectId', 'role', 'systemUserId', 'updatedAt'] as const
  $columns = ProjectMembershipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column()
  declare projectId: string
  @column()
  declare role: any
  @column()
  declare systemUserId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProjectSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'domain', 'id', 'isActive', 'name', 'phone', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domain: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RackAccessorySchema extends BaseModel {
  static $columns = ['accessoryTemplateId', 'createdAt', 'createdBy', 'deletedAt', 'deletedBy', 'heightU', 'id', 'kind', 'manufacturer', 'model', 'mountType', 'name', 'notes', 'projectId', 'rackId', 'unitStart', 'updatedAt', 'updatedBy'] as const
  $columns = RackAccessorySchema.$columns
  @column()
  declare accessoryTemplateId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: string | null
  @column()
  declare heightU: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare manufacturer: string | null
  @column()
  declare model: string | null
  @column()
  declare mountType: string
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare projectId: string
  @column()
  declare rackId: string
  @column()
  declare unitStart: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class RackAccessoryTemplateSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'defaultMountType', 'deletedAt', 'deletedBy', 'heightU', 'id', 'kind', 'manufacturer', 'model', 'name', 'notes', 'updatedAt', 'updatedBy'] as const
  $columns = RackAccessoryTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column()
  declare defaultMountType: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: string | null
  @column()
  declare heightU: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare manufacturer: string | null
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class RackSchema extends BaseModel {
  static $columns = ['areaId', 'code', 'createdAt', 'createdBy', 'deletedAt', 'deletedBy', 'heightU', 'id', 'manufacturer', 'model', 'name', 'notes', 'projectId', 'updatedAt', 'updatedBy'] as const
  $columns = RackSchema.$columns
  @column()
  declare areaId: string
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: string | null
  @column()
  declare heightU: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare manufacturer: string | null
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class SecretSchema extends BaseModel {
  static $columns = ['attachableId', 'attachableType', 'createdAt', 'createdBy', 'deletedAt', 'deletedBy', 'id', 'kind', 'label', 'notes', 'projectId', 'updatedAt', 'updatedBy', 'username', 'valueCiphertext'] as const
  $columns = SecretSchema.$columns
  @column()
  declare attachableId: string
  @column()
  declare attachableType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare label: string
  @column()
  declare notes: string | null
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
  @column()
  declare username: string | null
  @column()
  declare valueCiphertext: string
}

export class SiteSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'createdBy', 'deletedAt', 'deletedBy', 'id', 'name', 'notes', 'projectId', 'updatedAt', 'updatedBy'] as const
  $columns = SiteSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deletedBy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class SystemSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'logoMimeType', 'logoOriginalFilename', 'logoSizeBytes', 'logoStoragePath', 'reportTagline', 'updatedAt'] as const
  $columns = SystemSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logoMimeType: string | null
  @column()
  declare logoOriginalFilename: string | null
  @column()
  declare logoSizeBytes: bigint | number | null
  @column()
  declare logoStoragePath: string | null
  @column()
  declare reportTagline: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SystemUserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'firstName', 'id', 'isActive', 'lastName', 'password', 'projectId', 'role', 'updatedAt'] as const
  $columns = SystemUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare projectId: string
  @column()
  declare role: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TopologyCanvasLayoutSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'labelOffsets', 'layer', 'nodeParents', 'nodePositions', 'projectId', 'scope', 'updatedAt', 'workAreas'] as const
  $columns = TopologyCanvasLayoutSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare labelOffsets: any
  @column()
  declare layer: string
  @column()
  declare nodeParents: any
  @column()
  declare nodePositions: any
  @column()
  declare projectId: string
  @column()
  declare scope: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare workAreas: any
}

export class VlanSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'projectId', 'updatedAt', 'vlanId'] as const
  $columns = VlanSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vlanId: number
}
